title: "Vern's Blog"
url: http://du1abadd.org
permalink: "/:year/:categories/:title.html"
cloud_html: _includes/cloud.html
cloud_size: 100
cloud_max_ranks: 10
tags_directory: tags
pygments: false
lsi: false

markdown: pandoc
pandoc:
  extensions: [smart, standalone, toc]

asciidoc: asciidoctor
asciidoc_ext: asciidoc,adoc,ad
asciidoctor:
  safe: safe
  attributes:
    - notitle!
    - hardbreaks
    - coderay-css=style
    - source-highlighter=coderay
    - idprefix=
    - idseparator=-
    - linkattrs
    - imagesdir=/images
