# Configuration
# 同样实现了 markdown，区别在于 rdiscount/c 无扩展语法，maruku/ruby 带扩展语法
markdown: rdiscount
permalink: "/:year/:categories/:title.html"
pygments: true
lsi: false

# Custom variables
title: "Vern's Blog"
url: http://du1abadd.org
cloud_html: _includes/cloud.html
cloud_size: 100
cloud_max_ranks: 10
tags_directory: tags
