title: "Vern's Blog"
url: http://du1abadd.org
permalink: "/:year/:categories/:title.html"
cloud_html: _includes/cloud.html
cloud_size: 100
cloud_max_ranks: 10
tags_directory: tags
excerpt_separator: ""
highlighter: false
lsi: false

markdown: rdiscount

asciidoctor:
  safe: safe
  attributes:
    - notitle!
    - hardbreaks
    - coderay-css=style
    - source-highlighter=coderay
    - idprefix=
    - idseparator=-
    - linkattrs
    - imagesdir=/images

gems:
    - jekyll-pandoc
    - jekyll-asciidoc
#   - jekyll-tagging
#   - jekyll-tagging-related_posts
